CREATE TABLE [dbo].[Logement]
(
	[idLogement] INT IDENTITY NOT NULL, 
	[nom] NVARCHAR(50) NOT NULL, 
    [descriptionCourte] NVARCHAR(255) NOT NULL, 
    [descriptionLongue] NVARCHAR(MAX) NOT NULL, 
    [nbChambres] TINYINT NOT NULL DEFAULT 1, 
    [nbPieces] TINYINT NOT NULL DEFAULT 3, 
    [nbSDB] TINYINT NOT NULL DEFAULT 1, 
    [nbWC] TINYINT NOT NULL DEFAULT 1, 
    [balcon] BIT NOT NULL DEFAULT 0, 
    [airco] BIT NOT NULL DEFAULT 0, 
    [wifi] BIT NOT NULL DEFAULT 0, 
    [minibar] BIT NOT NULL DEFAULT 0, 
    [animauxAdmis] BIT NOT NULL DEFAULT 0, 
    [piscine] BIT NOT NULL DEFAULT 0, 
    [parking] BIT NOT NULL DEFAULT 0, 
    [voiturier] BIT NOT NULL DEFAULT 0, 
    [roomService] BIT NOT NULL DEFAULT 0, 
    [spa] BIT NOT NULL DEFAULT 0, 
    [prixNuitPersonne] MONEY NOT NULL, 
    [capacite] TINYINT NOT NULL DEFAULT 1,
    [longitude] DECIMAL(9,6) NOT NULL,
    [latitude] DECIMAL(8,6) NOT NULL,
    [rue] NVARCHAR(255) NOT NULL,
    [numero] NVARCHAR(10) NOT NULL, 
    [codePostal] NVARCHAR(10) NOT NULL, 
    [pays] CHAR(2) NOT NULL, 
    [dateAjout] DATE NOT NULL DEFAULT GETDATE(),
    [idCategorie] INT NOT NULL, 
    [idProprietaire] INT NOT NULL, 
    CONSTRAINT [PK_Logement] PRIMARY KEY ([idLogement]), 
    CONSTRAINT [CK_Logement_codePostal] CHECK (LEN(codePostal)>=4),
    CONSTRAINT [CK_Logement_rue] CHECK (LEN(rue)>=1),
    CONSTRAINT [CK_Logement_dateAjout] CHECK (dateAjout >= GETDATE()), 
    CONSTRAINT [FK_Logement_Categorie] FOREIGN KEY ([idCategorie]) REFERENCES [Categorie]([idCategorie]), 
    CONSTRAINT [FK_Logement_Proprietaire] FOREIGN KEY ([idProprietaire]) REFERENCES [Proprietaire]([idProprietaire])
)
